[package]
name = "turtle"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.32.0"
windows = { version = "0.61.3", features = ["Win32_Foundation", "Win32_UI_Shell"] }
urlencoding = "2.1.3"
meval = "=0.2.0"
